export enum ApprovalLimitPermissionCode{
  MedicalClaimPermissionCode ='Medical_Claims_Manager_Approval_Approve_Or_Deny_Payment_Requests',
  PharmacyPermissionCode ='Pharmacy_Claims_Manager_Approval_Approve_Or_Deny_Payment_Requests',
  InsurancePremiumPermissionCode ='Insurance_Premium_Manager_Approval_Approve_Or_Deny_Payment_Requests'
}
