export enum LovType {
    CaseOrigin = 'CASE_ORIGIN',
    Pronoun ='PRONOUNS',
    Material='MATERIAL_IN_ALTERNATE_FORMAT',
    MaterialYes='MATERIAL_IN_ALTERNATE_FORMAT_YES',
    PharmacyPriority='PHARMACY_PRIORITY',
    Gender ='Gender',
    Transgender ='Transgender',
    SexAtBirth ='SEX_AT_BIRTH',
    SexulaIdentity ='SEXUAL_IDENTITY',
    SpokenWrittenLanguage ='Spoken_Written_Language',
    EnglishProficiency ='English_Proficiency',
    RelationshipCode = 'RELATIONSHIP_CODE',
    ContactRelationshipCode = 'CONTACT_RELATIONSHIP_CODE',
    //RaceGroup = 'RACE,RACE_AND_ETHNICITY,RACE_ASIAN_SUBGROUP,RACE_ETHNICITY_OTHER_CATEGORIES,RACE_NATIVE_HAWAIIAN_AND_PACIFIC_ISLANDER',
    RaceGroup = 'ETHNICITY,RACE',
    Ethnicity = 'ETHNICITY',
	IncomeSource='INCOME_SOURCE_CODE',
  	Frequency='FREQUENCY_CODE',
  	IncomeType='INCOME_TYPE_CODE',
  	ProofOfIncomeType='PROOF_INCOME_TYPE_CODE',
    HealthInsuranceType ='HEALTH_INSURANCE_TYPE',
    MetalLevel ='METAL_LEVEL',
    PremiumFrequency = 'PREMIUM_FREQUENCY_CODE',
    MedicareCoverageType = 'MEDICARE_COVERAGE_TYPE_CODE',
    HEALTHINSURANCEPROOF = 'HEALTH_INSURANCE_PROOF',
    CaseStatusCode = 'CASE_STATUS_CODE'
  }
