export class ClientCaseEligibility{
        clientCaseEligibilityId :string | null = null;
        clientCaseId !:string;  
        eilgibilityStartDate? :Date;
        eligibilityEndDate? :Date;
        aka :string|null=null;
        insuranceFirstName :string|null=null;
        insuranceLastName :string|null=null;
        officialIdFirstName :string|null=null;
        officialIdLastName :string|null=null;
        groupCode :string|null=null;
        registerToVoteFlag !:string;
        clientTransgenderCode !:string;
        clientTransgenderDesc :string|null=null;
        materialInAlternateFormatCode !:string;
        materialInAlternateFormatDesc :string|null=null;
        spokenLanguageCode :string|null=null;
        writtenLanguageCode :string|null=null;
        englishProficiencyCode :string|null=null;
        interpreterCode :string|null=null;
        interpreterType :string|null=null;
        deafOrHearingCode :string|null=null;
        startAgeDeafOrHearing :number=0;
        blindSeeingCode :string|null=null;
        startAgeBlindSeeing :number=0;
        limitingConditionCode :string |null=null;
        startAgeLimitingCondition :number=0;
        walkingClimbingDifficultyCode :string|null=null;
        startAgeWalkingClimbingDifficulty :number=0;
        dressingBathingDifficultyCode :string|null=null;
        startAgeDressingBathingDifficulty :number=0;
        concentratingDifficultyCode :string|null=null;
        startAgeConcentratingDifficulty :number=0;
        errandsDifficultyCode :string|null=null;
        startAgeErrandsDifficulty :number=0;
        preferredContactCode :string|null=null;
        contactName :string|null=null;
        contactRelationshipCode :string|null=null;
        contactPhoneNbr :string|null=null;
        homelessFlag !:string;
        homeAddressProofFlag !:string;
        emailNotApplicableFlag !:string;
        noDependentFlag !:string;
        paperlessFlag !:string;
        noIncomeFlag !:string;
        noIncomeClientSignedDate? :Date;
        noIncomeSignatureNotedDate? :Date;
        noIncomeNote :string|null=null;
        unemployedFlag !:string;
        currentInsuranceFlag !:string;
        groupPolicyEligibleFlag !:string;
        smokingCessationReferralFlag !:string;
        smokingCessationNoteApplicableFlag !:string;
        smokingCessationNote :string|null=null;
        hivPrescriptionFlag !:string;
        nonPreferredPharmacyFlag !:string;
        eligibilityStatusCode :string|null=null;
        waitlistStatusCode :string|null=null;
        serviceCoordinationRegionCode :string|null=null;
        serviceCoordinationHcId :number=0;
        serviceCoordinatorServicePointId :number=0;
        fplPercentage :number=0;
        justMemo :string='';
        creatorId :string | null= null;
        creationTime? :Date | null = null;
        lastModifierId :string | null= null;
        lastModificationTime? :Date | null = null;
        isDeleted :boolean=false;
        deleterId :string | null = null;
        deletionTime? :Date | null = null;
        extraProperties :string | null = null;
        concurrencyStamp :string='';
}