export class Client {
  clientId :number =0;
  firstName :string='';
  middleName :string='';
  //noMiddleNameFlag :string='';
  lastName :string='';
  clientFullName :string='';
  dob? :Date= new Date;
  ssn :string='';
  ssnNotApplicableFlag :string='';
  genderAtBirthCode :string='';
  genderAtBirthDesc :string='';
  urn :string='';
  encryptedUrn :string='';
  medicareEligibleDate :Date=new Date;
  genderType :string='';
  clientTransgenderCode :string='';
  clientTransgenderDesc :string='';
  materialInAlternateFormatCode :string='';
  materialInAlternateFormatDesc :string='';
  spokenLanguageCode :string='';
  writtenLanguageCode :string='';
  englishProficiencyCode :string='';
  interpreterCode :string='';
  interpreterType :string='';
  deafOrHearingCode :string='';
  startAgeDeafOrHearing :number=0;
  blindSeeingCode :string='';
  startAgeBlindSeeing :number=0;
  limitingConditionCode :string='';
  startAgeLimitingCondition :number=0;
  walkingClimbingDifficultyCode :string='';
  startAgeWalkingClimbingDifficulty :number=0;
  dressingBathingDifficultyCode :string='';
  startAgeDressingBathingDifficulty :number=0;
  concentratingDifficultyCode :string='';
  startAgeConcentratingDifficulty :number=0;
  errandsDifficultyCode :string='';
  startAgeErrandsDifficulty :number=0;
  preferredContactCode :string='';
  contactName :string='';
  contactRelationshipCode :string='';
  contactPhoneNbr :string='';
  // creatorId :string='';
  // creationTime? :Date=new Date;
  // lastModifierId :string='';
  // lastModificationTime? :Date;
  // isDeleted :boolean=false;
  // deleterId :string='';
  // deletionTime? :Date=new Date;
  // extraProperties :string='';
  // concurrencyStamp :string='';
  activeFlag :string='';
}

export interface SpecialHandling {
  id: number;
  specialHandling: string;
  answer: string;
}
