export interface Dependent {
    clientRelationshipId  :  string  ,
    clientId  : number,
    relationshipTypeCode  :  string  ,
    relationshipSubTypeCode  :    string  ,
    OtherDesc    : string
    firstName  :    string  ,
    lastName  :   string  ,
    fullName  :   string  ,
    ssn  :    string  ,
    dob  :   Date  ,
    age : string ,
    phoneNbr  :    string  ,
    effectiveDate  :    string  ,
    hivPositiveFlag  :   string  ,
    enrolledInInsuranceFlag  :   string  ,
    justMemo  :    string  ,
    finMemo  :   string  ,
    proContactFlag  :    string  ,    
    concurrencyStamp  :  string  ,
    activeFlag  :    string    ,
    isCareAssistFlag : string  ,
    memberType : string,
    fullCustomName :string,
    dependentClientId : string,
    clientCaseEligibilityId: string,
}