export interface Dependent {
    clientDependentId  :  string  ,
    clientId  : number,
    dependentTypeCode  :  string  ,
    relationshipCode  :    string  ,
    relationshipDescription    : string
    firstName  :    string  ,
    lastName  :   string  ,
    fullName  :   string  ,
    ssn  :    string  ,
    dob  :   Date  ,
    age : string ,
    phoneNbr  :    string  ,
    effectiveDate  :    string  ,
    hivPositiveFlag  :   string  ,
    enrolledInInsuranceFlag  :   string  ,
    justMemo  :    string  ,
    finMemo  :   string  ,
    proContactFlag  :    string  ,    
    concurrencyStamp  :  string  ,
    activeFlag  :    string    ,
    isCareAssistFlag : string  ,
    memberType : string,
    fullCustomName :string
}
