import { Dependent } from "./dependent";

export class HealthInsurancePolicy {
        clientInsurancePolicyId: string | null = null;
        clientId: number | null = null;
        insuranceVendorId: string | null = null;
        clientCaseEligibilityId: string | null = null;
        insurancePlanId: string | null = null;
        clientMaximumId: string | null = null;
        healthInsuranceTypeCode: string | null = null;
        insuranceIdNbr: string | null = null;
        insuranceGroupPlanTypeCode: string | null = null;
        insuranceGroupId:string | null = null;
        priorityCode: string | null = null;
        policyHolderFirstName: string | null = null;
        policyHolderLastName: string | null = null;
        metalLevelCode: string | null = null;
        premiumAmt: number | null = null;
        insuranceStartDate?: string | null;
        insuranceEndDate?: string | null;
        careassistPayingPremiumFlag: string | null = null;
        premiumPaidThruDate?: string | null;
        premiumFrequencyCode: string | null = null;
        nextPremiumDueDate?: string | null;
        paymentIdNbrSameAsInsuranceIdNbrFlag: string | null = null;
        paymentIdNbr: string | null = null;
        aptcCode: string | null = null;
        aptcNotTakingFlag: string | null = null;
        aptcMonthlyAmt: number | null = null;
        othersCoveredOnPlanFlag: string | null = null;
        isClientPolicyHolderFlag: string | null = null;
        medicareBeneficiaryIdNbr: string | null = null;
        medicareCoverageTypeCode: string | null = null;
        medicarePartAStartDate?: string | null;
        medicarePartBStartDate?: string | null;
        medicareEndDate?: string | null;
        onQmbFlag: string | null = null;
        onLisFlag: string | null = null;
        paymentGroupNumber: number | null = null;
        insuranceFirstName: string | null = null;
        insuranceLastName: string | null = null;
        oonException: number | null = null;
        oonStartDate?: string;
        oonEndDate?: string;
        oonPharmacy: string | null = null;
        oonDrugs: string | null = null;
        concurrencyStamp: string | null = null;
        activeFlag: string | null = null;
        creationTime?: string;
        proofOfPremiumFile: any = null;
        proofOfPremiumFileName: string = "";
        proofOfPremiumFileSize: number | null = null;
        proofOfPremiumFileTypeCode: string = "";
        proofOfPremiumFileId: string = "";
        proofOfPremiumFilePath: string = "";
        copyOfInsuranceCardFile: any = null;
        copyOfInsuranceCardFileName: string = "";
        copyOfInsuranceCardFileSize: number | null = null;
        copyOfInsuranceCardFileTypeCode: string = "";
        copyOfInsuranceCardFileId: string = "";
        copyOfInsuranceCardFilePath: string = "";
        copyOfSummaryFile: any = null;
        copyOfSummaryFileName: string = "";
        copyOfSummaryFileSize: number | null = null;
        copyOfSummaryFileTypeCode: string = "";
        copyOfSummaryFileId: string = "";
        copyOfSummaryFilePath: string = "";
        medicareCardFile: any = null;
        medicareCardFileName: string = "";
        medicareCardFileSize: number | null = null;
        medicareCardFileTypeCode: string = "";
        medicareCardFileId: string = "";
        medicareCardFilePath: string = "";        
        othersCoveredOnPlan: Array<Dependent> = [];
        isCerReview: boolean = false;
        insuranceVendorAddressId: string | null = null;
        insuranceTypeCode: string | null = null;
        //removedOthersCoveredOnPlan: Array<othersCoveredOnPlan> = [];
}

export class OthersCoveredOnPlan {
        relationshipDescription: string = "";
        relationshipCode: string = "";
        firstName: string = "";
        lastName: string = "";
        dob?: string;
        enrolledInInsuranceFlag: string = "";
}
