export enum SystemInterfaceEventGroup {
    SYSTEM_INTERFACE_EXTERNAL = "SYSTEM_INTERFACE_EXTERNAL",
    SYSTEM_INTERFACE_INTERNAL = "SYSTEM_INTERFACE_INTERNAL" ,
    CATEGORY_1 = "CATEGORY_1",
    CATEGORY_2 = "CATEGORY_2",
    CATEGORY_3 = "CATEGORY_3",
    };