export enum EventTypeCode {
    CerAuthorizationLetter="CER_AUTHORIZATION_LETTER",    
    ApplicationAuthorizationLetter="APPLICATION_AUTHORIZATION_LETTER",
    ManufacuterLetter="MANUFACTURER_LETTER",
    InsuranceVendorLetter="INSURANCE_VENDOR_LETTER",
    MedicalProviderLetter="MEDICAL_PROVIDER_LETTER",
    PharmacyLetter="PHARMACY_LETTER",
    DentalProviderLetter="DENTAL_PROVIDER_LETTER",
    ClientLetter="LETTER",
    VendorLetter="VENDOR_LETTER",
    LETTER="Letter",
    LetterTypeCode="CLIENT_LETTER",
    PendingNoticeLetter = 'PENDING_NOTICE_LETTER',
    CerPendingLetterGenerated = 'CER_PENDING_LETTER_GENERATED',
    RejectionNoticeLetter = 'REJECTION_NOTICE_LETTER',
    RejectionLetterGenerated = 'REJECTION_LETTER_GENERATED',
    ApprovalNoticeLetter = 'APPROVAL_NOTICE_LETTER',
    ApprovalLetterGenerated = 'APPROVAL_LETTER_GENERATED',
    CerApprovalLetterGenerated = 'CER_APPROVAL_LETTER_GENERATED',
    CerApprovalEmailSent = 'CER_APPROVAL_EMAIL_SENT',
    DisenrollmentNoticeLetter = 'DISENROLLMENT_NOTICE_LETTER',
    DisenrollmentLetterGenerated = 'DISENROLLMENT_LETTER_GENERATED',
    VendorLetterCreated = 'VENDOR_LETTER_CREATED',
    ClientLetterCreatedt = 'CLIENT_LETTER_CREATED',
    ApplicationAndCERLetterSent = 'LETTER_SENT',
    CerLetterSent = "CER_LETTER_SENT"
  }
