export enum ClientProfileTabs {
    CLIENT_INFO = "clt-info",
    CLIENT_CONTACT_INFO = "clt-cntct-info",
    CLIENT_FAMILY_DEPENDENTS = "clt-fmly-depndnt",
    CLIENT_INCOME = "clt-inc",
    CLIENT_SMOKING_CESS= 'clt-smk' ,
    CLIENT_EMPLOYMENT = "clt-emp",
    HEALTH_INS='hlt_ins',
    HEALTH_INSURANCE_STATUS='hlt-ins-st',
    HEALTH_INSURANCE_PREMIUM_PAYMENTS='hlt-ins-prm-pym',
    HEALTH_INSURANCE_COPAY='hlt-ins-co-pay',
    DENTAL_INSURANCE_STATUS='dnt-ins-st',
    DENTAL_INSURANCE_PREMIUM_PAYMENTS='dnt-ins-prm-pym',
    DENTAL_INSURANCE_COPAY='dnt-ins-co-pay',
    DRUGS='drg',
    DRUGS_PHARMACIES = 'drg-phrmc',
    DRUGS_PURCHASED = 'drg-prcd', 
    MANAGEMENT ='mngmt',
    MANAGEMENT_MANAGER ='mngmt-mngr',
    MANAGEMENT_PROVIDER ='mngmt-prvdr',
    MANAGEMENT_CD4 ='mngmt-cd4',
    MANAGEMENT_VRL ='mngmt-vrl',
    STATUS_PERIOD ='sts-prd',
    ATTACHMENTS ='attch',
    APP_HISTORY='history'
}
