export enum ScreenType {
  Authorization = 'Authorization',
  Case360Page = 'Case360Page',
  ApplicationEligibility = 'application-eligibility',
  SendLetter = 'send-letter',
  Eligibility = 'eligibility',
  CaseDetailPage = 'case-detail',
  Case360PageEmail = 'Case360PageEmail',
  Case360PageLetter = 'Case360PageLetter',
  Case360PageSMS = 'Case360PageSMS',
  VendorLetter = 'VendorLetter',
  VendorEmail = 'VendorEmail',
  VendorProfile = 'VENDOR_PROFILE',
  ClientProfile = 'CLIENT_PROFILE',
}
