import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { ConfigurationProvider } from '@cms/shared/util-core'; 
import { Observable, of } from 'rxjs';
@Injectable({
  providedIn: 'root',
})
export class SystemInterfaceSupportService {
  constructor(private readonly http: HttpClient,
    private configurationProvider : ConfigurationProvider) {}

  getSupportGroup(): Observable<any> {
    return of([
      {
        id: 1,
        interface: 'McKesson',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Failed',
        totalRecords: 100,
        failedRecords: 4,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 2,
        interface: 'OHA',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 3,
        interface: 'Kaiser',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
    ]);
  }
  getDistributionLists(): Observable<any> {
    return of([
      {
        id: 1,
        interface: 'McKesson',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Failed',
        totalRecords: 100,
        failedRecords: 4,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 2,
        interface: 'OHA',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 3,
        interface: 'Kaiser',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
    ]);
  }

  loadNotificationCategoryServices() {
    return of([
      {
        id: 1,
        interface: 'McKesson',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Failed',
        totalRecords: 100,
        failedRecords: 4,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 2,
        interface: 'OHA',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 3,
        interface: 'Kaiser',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
      {
        id: 4,
        interface: 'Surveillance',
        process: 'Order',
        processStartDate: 'MM/DD/YYYY',
        processEndDate: 'MM/DD/YYYY',
        status: 'Success',
        totalRecords: 100,
        failedRecords: 0,
        stampDate: 'MM/DD/YYYY',
        standTime: '00:00:00 AM',
      },
    ]);
  }

  
}